export const userData = {
  nombre: 'Nombre Apellido',
  nivel: 'Basico',
  lenguaje: 'Python',
  ejerciciosCompletados: 0,
  ejerciciosTotal: 10,
  sugerencia: 'Es recomendado practicar condicionales',
}

export const modulos = [
  {
    id: 1,
    titulo: 'Variables básicas',
    nivel: 'Básico',
    progreso: 0,
    progresoTotal: 6,
    desbloqueado: true,
    ejercicios: [
      { id: 'ia-1', tipo: 'ia', texto: 'Prácticas generadas por IA', estado: 'ia' },
      { id: 'e1-1', tipo: 'ejercicio', texto: 'Introducción a variables', estado: 'disponible' },
      { id: 'e1-2', tipo: 'ejercicio', texto: 'Tipos de datos básicos', estado: 'disponible' },
      { id: 'e1-3', tipo: 'ejercicio', texto: 'Asignación de valores', estado: 'disponible' },
      { id: 'e1-4', tipo: 'ejercicio', texto: 'Operaciones simples', estado: 'disponible' },
      { id: 'e1-5', tipo: 'ejercicio', texto: 'Uso de variables en cálculos', estado: 'disponible' },
      { id: 'e1-6', tipo: 'ejercicio', texto: 'Entrada de datos (input)', estado: 'disponible' },
    ],
  },
  {
    id: 2,
    titulo: 'Condicionales',
    nivel: 'Básico - Intermedio',
    progreso: 0,
    progresoTotal: 8,
    desbloqueado: true,
    ejercicios: [
      { id: 'ia-2', tipo: 'ia', texto: 'Prácticas generadas por IA', estado: 'ia' },
      { id: 'e2-1', tipo: 'ejercicio', texto: 'Introducción a condicionales', estado: 'disponible' },
      { id: 'e2-2', tipo: 'ejercicio', texto: 'Estructura if', estado: 'disponible' },
      { id: 'e2-3', tipo: 'ejercicio', texto: 'Condiciones simples', estado: 'disponible' },
      { id: 'e2-4', tipo: 'ejercicio', texto: 'Uso de operadores lógicos', estado: 'disponible' },
      { id: 'e2-5', tipo: 'ejercicio', texto: 'Condicionales con input', estado: 'disponible' },
      { id: 'e2-6', tipo: 'ejercicio', texto: 'Decisiones básicas en problemas', estado: 'disponible' },
      { id: 'e2-7', tipo: 'ejercicio', texto: 'Condicionales anidados', estado: 'bloqueado' },
      { id: 'e2-8', tipo: 'ejercicio', texto: 'Resolución de problemas con condicionales', estado: 'bloqueado' },
    ],
  },
  {
    id: 3,
    titulo: 'Lógica de programación',
    nivel: 'Básico - Intermedio',
    progreso: 0,
    progresoTotal: 6,
    desbloqueado: false,
    ejercicios: [
      { id: 'ia-3', tipo: 'ia', texto: 'Prácticas generadas por IA', estado: 'ia' },
      { id: 'e3-1', tipo: 'ejercicio', texto: 'Análisis de problemas simples', estado: 'bloqueado' },
      { id: 'e3-2', tipo: 'ejercicio', texto: 'Identificación de variables necesarias', estado: 'bloqueado' },
      { id: 'e3-3', tipo: 'ejercicio', texto: 'Diseño de solución paso a paso', estado: 'bloqueado' },
      { id: 'e3-4', tipo: 'ejercicio', texto: 'Implementación de lógica básica', estado: 'bloqueado' },
      { id: 'e3-5', tipo: 'ejercicio', texto: 'Resolución de problemas con condiciones', estado: 'bloqueado' },
      { id: 'e3-6', tipo: 'ejercicio', texto: 'Resolución de problemas con iteraciones', estado: 'bloqueado' },
    ],
  },
  {
    id: 4,
    titulo: 'Funciones y modularización',
    nivel: 'Intermedio',
    progreso: 0,
    progresoTotal: 8,
    desbloqueado: false,
    ejercicios: [
      { id: 'ia-4', tipo: 'ia', texto: 'Prácticas generadas por IA', estado: 'ia' },
      { id: 'e4-1', tipo: 'ejercicio', texto: 'Introducción a Funciones', estado: 'bloqueado' },
      { id: 'e4-2', tipo: 'ejercicio', texto: 'Definir funciones simples', estado: 'bloqueado' },
      { id: 'e4-3', tipo: 'ejercicio', texto: 'Funciones con parámetros', estado: 'bloqueado' },
      { id: 'e4-4', tipo: 'ejercicio', texto: 'Retorno de valores', estado: 'bloqueado' },
      { id: 'e4-5', tipo: 'ejercicio', texto: 'Uso de funciones en cálculos', estado: 'bloqueado' },
      { id: 'e4-6', tipo: 'ejercicio', texto: 'Separación de lógica en funciones', estado: 'bloqueado' },
      { id: 'e4-7', tipo: 'ejercicio', texto: 'Funciones que resuelven problemas simples', estado: 'bloqueado' },
      { id: 'e4-8', tipo: 'ejercicio', texto: 'Problema integrador con funciones', estado: 'bloqueado' },
    ],
  },
  {
    id: 5,
    titulo: 'Bucles y repetición',
    nivel: 'Intermedio',
    progreso: 0,
    progresoTotal: 8,
    desbloqueado: false,
    ejercicios: [
      { id: 'ia-5', tipo: 'ia', texto: 'Prácticas generadas por IA', estado: 'ia' },
      { id: 'e5-1', tipo: 'ejercicio', texto: 'Introducción a bucles', estado: 'bloqueado' },
      { id: 'e5-2', tipo: 'ejercicio', texto: 'Uso del bucle while', estado: 'bloqueado' },
      { id: 'e5-3', tipo: 'ejercicio', texto: 'Uso del bucle for', estado: 'bloqueado' },
      { id: 'e5-4', tipo: 'ejercicio', texto: 'Contadores y acumuladores', estado: 'bloqueado' },
      { id: 'e5-5', tipo: 'ejercicio', texto: 'Uso de bucles con condicionales', estado: 'bloqueado' },
      { id: 'e5-6', tipo: 'ejercicio', texto: 'Iteración sobre listas simples', estado: 'bloqueado' },
      { id: 'e5-7', tipo: 'ejercicio', texto: 'Resolución de problemas con bucles', estado: 'bloqueado' },
      { id: 'e5-8', tipo: 'ejercicio', texto: 'Problema integrador con iteraciones', estado: 'bloqueado' },
    ],
  },
  {
    id: 6,
    titulo: 'Resolución de problemas integrados',
    nivel: 'Intermedio - Avanzado',
    progreso: 0,
    progresoTotal: 6,
    desbloqueado: false,
    ejercicios: [
      { id: 'ia-6', tipo: 'ia', texto: 'Prácticas generadas por IA', estado: 'ia' },
      { id: 'e6-1', tipo: 'ejercicio', texto: 'Problemas con múltiples condiciones', estado: 'bloqueado' },
      { id: 'e6-2', tipo: 'ejercicio', texto: 'Uso de estructuras de repetición en problemas', estado: 'bloqueado' },
      { id: 'e6-3', tipo: 'ejercicio', texto: 'Descomposición de problemas en funciones', estado: 'bloqueado' },
      { id: 'e6-4', tipo: 'ejercicio', texto: 'Validación de datos de entrada', estado: 'bloqueado' },
      { id: 'e6-5', tipo: 'ejercicio', texto: 'Optimización de soluciones simples', estado: 'bloqueado' },
      { id: 'e6-6', tipo: 'ejercicio', texto: 'Problema integrador completo', estado: 'bloqueado' },
    ],
  },
]
